Only woman
A1-frkweiichi/mokumoku pull request #1
Opened 2023-02-25 07:03 UTC by furukawaeiichi

2/25

2023-02-26 05:12 UTC, furukawaeiichi commented
こちらRepecスクリーンショットです。ご確認いただけましたら幸いです。
[![Image from Gyazo](https://i.gyazo.com/095c368684163ad6e5d1016d85db535c.png)](https://gyazo.com/095c368684163ad6e5d1016d85db535c)

2023-02-26 07:18 UTC, masa-oh reviewed
2点コメントしましたので、ご確認ください！
また、`.DS_Store`、`spec/.DS_Store`という余計なファイルが含まれているので、これらがコミットに含まれないよう変更できますか？

2023-02-26 07:18 UTC, masa-oh commented on app/models/user.rb
> +    gender = "woman"
このメソッドは必要でしょうか？

2023-02-26 07:18 UTC, masa-oh commented on app/views/events/show.html.erb
> +                  <% end %>
ifブロックとelseブロックで全く同じ内容を表示するのであれば、elseによる条件分岐は必要なさそうですね。
if文の条件で`&&`や`||`を使えば、綺麗に書けないでしょうか？

2023-02-26 08:54 UTC, furukawaeiichi commented on app/views/events/show.html.erb
> +                  <% end %>
レビューありがとうございます！
すみません。色々考えているのですが、自身ではきれいに書けたつもりです。。
どこのことを指しているのか、もう少しヒントをいただけませんでしょうか？

2023-02-26 12:32 UTC, furukawaeiichi commented
修正後のRspecも通っています。
[![Image from Gyazo](https://i.gyazo.com/90da45ef2e4912747be22bbc353505fe.png)](https://gyazo.com/90da45ef2e4912747be22bbc353505fe)

2023-02-27 10:44 UTC, busitora requested changes

2023-02-27 10:44 UTC, busitora commented on app/views/events/show.html.erb
> +                  <% end %>
```ruby
                    <%= link_to 'このもくもく会に参加する',
                                event_attendance_url(@event),
                                class: 'btn btn-primary',
                                method: :post,
                                data: { confirm: '申し込みます' }
```
この部分が同じ表記なのであれば、`!@event.only_woman?` or  `@event.only_woman? && current_user.woman?` となります、

特定の条件の場合のみ、 その link_to を生成するのであれば、 elsif ではなく
> if文の条件で&&や||を使えば、綺麗に書けないでしょうか？

上記ができますね！

2023-02-28 05:23 UTC, furukawaeiichi commented
busitora先生
コメントありがとうございました！！！

簡素化して、再度Rspec通りましたので、ご確認いただけたら幸いです。
[![Image from Gyazo](https://i.gyazo.com/3d1df96ad2f55874e146fdd5d3dec69c.png)](https://gyazo.com/3d1df96ad2f55874e146fdd5d3dec69c)

2023-02-28 12:18 UTC, enda1111 approved these changes
LGTMです！

2023-02-28 13:47 UTC, furukawaeiichi commented
レビューありがとうございました！！！

2023-02-28 13:57 UTC, merged